name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker nvm image
      run: docker build . --file images/nvm/Dockerfile --tag ubuntu2204-nvm:$(date +%s)
    - name: Build the Docker base image
      run: docker build . --file images/base/Dockerfile --tag ubuntu2204-base:$(date +%s)
